[package]
name = "fps_tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.16", features = ["dynamic_linking", "jpeg"] }
bevy_rapier3d = "0.30"
bevy_fps_controller = "0.16"
rand = "0.8.5"
[profile.dev]
opt-level = 1
